name: discount_and_currency_calculator
description: "Aplikasi Kalkulator Diskon"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  hive_generator:

flutter:
  uses-material-design: true
  assets:
   - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  background_color: "#6b6b6b"
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#6b6b6b"